#!/bin/bash
# Copyright (C) 2015
# Bob Mottram <bob@robotucs.uk.to>
#
# This script lists Avahi peers
#
# toxbot is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# toxbot is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with toxbot. If not, see <http://www.gnu.org/licenses/>.

PEERS_FILE=/tmp/lsmeshpeers.txt
TEMPDIR=/home/$USER/.avahipeers
if [ -d $TEMPDIR ]; then
    rm -rf $TEMPDIR
fi

avahi-browse -atl | grep "Workstation" | awk -F ' ' '{print $4}' | sort -u > $PEERS_FILE
if [ ! "$?" = "0" ]; then
    exit 1
fi

if [ ! -f $PEERS_FILE ]; then
   exit 0
fi

mkdir $TEMPDIR
while IFS='' read -r line || [[ -n "$line" ]]; do
    touch $TEMPDIR/$line
done < "$PEERS_FILE"

ls $TEMPDIR

rm -rf $TEMPDIR
rm $PEERS_FILE
exit 0
