#!/bin/bash
# Copyright (C) 2015
# Bob Mottram <bob@robotucs.uk.to>
#
# Lists Tox users
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

USERS_FILE=/tmp/lsmeshusers.txt
TEMPDIR=/home/$USER/.avahiusers
if [ -d $TEMPDIR ]; then
    rm -rf $TEMPDIR
fi

avahi-browse -atl | grep "Tox User" | awk -F '(' '{print $2}' | awk -F ')' '{print $1}' | sort -u > $USERS_FILE
if [ ! "$?" = "0" ]; then
    exit 1
fi

if [ ! -f $USERS_FILE ]; then
   exit 0
fi

mkdir $TEMPDIR
while IFS='' read -r line || [[ -n "$line" ]]; do
    touch $TEMPDIR/$line
done < "$USERS_FILE"

ls $TEMPDIR

rm -rf $TEMPDIR
rm $USERS_FILE
exit 0
