#!/bin/bash

PEERNAME=
if [ $1 ]; then
    # show the Tox ID for a specific peer
    PEERNAME=$1
fi

if [ ! -d /etc/avahi ]; then
    exit 0
fi

TEMPFILE=/tmp/toxavahi.txt
avahi-browse -atr | grep " Tox\|address =\|port =\|txt =" > $TEMPFILE
if [ ! -f $TEMPFILE ]; then
    exit 1
fi

state=0
address=""
port=0
peer=""
while IFS='' read -r line || [[ -n "$line" ]]; do
    if [ ${state} -eq "3" ]; then
        if [[ $line == *"txt ="* ]]; then
            id=$(echo $line | awk -F '"' '{print $2}')
            if [ ! $PEERNAME ]; then
                echo "$address $port $id"
            else
                echo "$address"
            fi
            state=0
        fi
    fi
    if [ ${state} -eq "2" ]; then
        if [[ $line == *"port ="* ]]; then
            if [ ! $PEERNAME ]; then
                port=$(echo $line | awk -F '[' '{print $2}' | awk -F ']' '{print $1}')
            fi
            state=3
        fi
    fi
    if [ ${state} -eq "1" ]; then
        if [[ $line == *"hostname ="* && $PEERNAME ]]; then
            peer=$(echo $line | awk -F '[' '{print $2}' | awk -F ']' '{print $1}')
            if [[ $peer != "${PEERNAME}.local" ]]; then
                state=0
            fi
        fi
        if [[ $line == *"address ="* ]]; then
            address=$(echo $line | awk -F '[' '{print $2}' | awk -F ']' '{print $1}')
            state=2
        fi
    fi
    if [[ $line == *" Tox"* && $line == *"= "* ]]; then
        state=1
    fi
done < "$TEMPFILE"

rm -f $TEMPFILE

exit 0
