#!/bin/bash
USERS_FILE=/tmp/lsmeshusers.txt
TEMPDIR=/home/$USER/.avahiusers
if [ -d $TEMPDIR ]; then
    rm -rf $TEMPDIR
fi

avahi-browse -atl | grep "Tox User" | awk -F '(' '{print $2}' | awk -F ')' '{print $1}' | sort -u > $USERS_FILE
if [ ! "$?" = "0" ]; then
    exit 1
fi

if [ ! -f $USERS_FILE ]; then
   exit 0
fi

mkdir $TEMPDIR
while IFS='' read -r line || [[ -n "$line" ]]; do
    touch $TEMPDIR/$line
done < "$USERS_FILE"

ls $TEMPDIR

rm -rf $TEMPDIR
rm $USERS_FILE
exit 0
