#!/bin/bash
# Copyright (C) 2015
# Bob Mottram <bob@robotucs.uk.to>
#
# This script publishes tox user IDs to the local network
# via Avahi. It could be regularly called from cron
#
# For example:
#     echo "* *       * * *   root    toxavahi > /dev/null" >> /etc/crontab
#
# toxbot is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# toxbot is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with toxbot. If not, see <http://www.gnu.org/licenses/>.

TOX_PORT=33445
DHTNODES=/usr/local/share/toxic/DHTnodes
QTOX_INI='.config/tox/qtox.ini'
TOX_BOOTSTRAP_ID_FILE=/var/lib/tox-bootstrapd/pubkey.txt

for userdir in /home/*/; do

    MY_USERNAME=$(echo $userdir | awk -F '/' '{print $3}')

    # is there a tox configuration for this user?
    DATA_FILE=/home/$MY_USERNAME/.config/tox/data
    if [ ! -f $DATA_FILE ]; then
        continue
    fi

    if [ -f /home/$MY_USERNAME/$QTOX_INI ]; then
        # keep a copy of the original settings
        if [ ! -f /home/$MY_USERNAME/$QTOX_INI.internet ]; then
            cp /home/$MY_USERNAME/$QTOX_INI /home/$MY_USERNAME/$QTOX_INI.internet
        fi
        if [ -f /home/$MY_USERNAME/$QTOX_INI.new ]; then
            rm /home/$MY_USERNAME/$QTOX_INI.new
        fi
        # get tox nodes from avahi
        nodeslist=$(lstox -f qtox)
        if [ $(echo $nodeslist | wc -l) -eq "0" ]; then
            # if there are no avahi nodes
            cp /home/$MY_USERNAME/$QTOX_INI.internet /home/$MY_USERNAME/$QTOX_INI
        else
            # update the list with tox nodes from avahi
            writeline="yes"
            while IFS='' read -r line || [[ -n "$line" ]]; do
                if [[ $writeline == "yes" ]];
                   echo $line >> /home/$MY_USERNAME/$QTOX_INI.new
                   if [[ $line == "[DHT"* ]]; then
                       writeline="no"
                       echo $nodeslist >> /home/$MY_USERNAME/$QTOX_INI.new
                       echo '' >> /home/$MY_USERNAME/$QTOX_INI.new
                   fi
                else
                    if [[ $line == "["* ]]; then
                        writeline="yes"
                        echo $line >> /home/$MY_USERNAME/$QTOX_INI.new
                    fi
                fi
            done < "/home/$MY_USERNAME/$QTOX_INI.internet"
            cp -f /home/$MY_USERNAME/$QTOX_INI.new /home/$MY_USERNAME/$QTOX_INI
            rm /home/$MY_USERNAME/$QTOX_INI.new
        fi
    fi

    TOX_ID=$(toxid -u $MY_USERNAME)

    echo '<?xml version="1.0" standalone="no"?><!--*-nxml-*-->' > /etc/avahi/services/tox-${MY_USERNAME}.service
    echo '<!DOCTYPE service-group SYSTEM "avahi-service.dtd">' >> /etc/avahi/services/tox-${MY_USERNAME}.service
    echo '<service-group>' >> /etc/avahi/services/tox-${MY_USERNAME}.service
    echo "  <name replace-wildcards='yes'>%h Tox User ($MY_USERNAME)</name>" >> /etc/avahi/services/tox-${MY_USERNAME}.service
    echo '  <service>' >> /etc/avahi/services/tox-${MY_USERNAME}.service
    echo '    <type>_tox._tcp</type>' >> /etc/avahi/services/tox-${MY_USERNAME}.service
    echo "    <port>$TOX_PORT</port>" >> /etc/avahi/services/tox-${MY_USERNAME}.service
    echo "    <txt-record>$TOX_ID</txt-record>" >> /etc/avahi/services/tox-${MY_USERNAME}.service
    echo '  </service>' >> /etc/avahi/services/tox-${MY_USERNAME}.service
    echo '</service-group>' >> /etc/avahi/services/tox-${MY_USERNAME}.service

done

if [ -f $TOX_BOOTSTRAP_ID_FILE ]; then
    TOX_BOOTSTRAP_ID=$(cat $TOX_BOOTSTRAP_ID_FILE)
    if [ ${#TOX_BOOTSTRAP_ID} -gt 30 ]; then
        echo '<?xml version="1.0" standalone="no"?><!--*-nxml-*-->' > /etc/avahi/services/tox-bootstrap.service
        echo '<!DOCTYPE service-group SYSTEM "avahi-service.dtd">' >> /etc/avahi/services/tox-bootstrap.service
        echo '<service-group>' >> /etc/avahi/services/tox-bootstrap.service
        echo "  <name replace-wildcards='yes'>%h Tox Bootstrap</name>" >> /etc/avahi/services/tox-bootstrap.service
        echo '  <service>' >> /etc/avahi/services/tox-bootstrap.service
        echo '    <type>_tox._tcp</type>' >> /etc/avahi/services/tox-bootstrap.service
        echo "    <port>$TOX_PORT</port>" >> /etc/avahi/services/tox-bootstrap.service
        echo "    <txt-record>$TOX_BOOTSTRAP_ID</txt-record>" >> /etc/avahi/services/tox-bootstrap.service
        echo '  </service>' >> /etc/avahi/services/tox-bootstrap.service
        echo '</service-group>' >> /etc/avahi/services/tox-bootstrap.service
    fi
fi

if [ -f $DHTNODES ]; then
    lstox -f dht > $DHTNODES
fi

exit 0
